#!/usr/bin/env bash

ORIG_DIR=`pwd`
function return_to_orig {
    cd "${ORIG_DIR}"
}

trap return_to_orig EXIT

GHOST_CONTENT_DIR="${GHOST_CONTENT_DIR:-'/var/lib/ghost/content/'}"

GHOST_BACKUP_DIRECTORY="${GHOST_BACKUP_DIRECTORY:-'/var/lib/ghost/backup/'}"

CURRENT_DATE=`date +"%Y-%m-%d"`

FILENAME="ghost-backup-${CURRENT_DATE}.tar.giz"

mkdir -p "${GHOST_BACKUP_DIRECTORY}"

cd  "${GHOST_CONTENT_DIR}"

tar czf "${FILENAME}" .

mv "${FILENAME}" "${GHOST_BACKUP_DIRECTORY}"
